# -*- coding: utf-8 -*-

import unittest
import os

# 旧版
# from HTMLTestRunner import HTMLTestRunner

# 新版
from BeautifulReport import BeautifulReport

# from case_unittest.test_case_by_json import TestMathFunc


# 输出为文本格式
# if __name__=='__main__':
#     suite=unittest.TestSuite()
#
#     tests=[TestMathFunc("test_add"),TestMathFunc("test_minus"),TestMathFunc("test_divide"),TestMathFunc("test_multi")]
#     suite.addTests(tests)
#
#     with open('UnittestTextReport.txt','a')as f:
#         runner=unittest.TextTestRunner(stream=f,verbosity=2)
#         runner.run(suite)


# 按照加载顺序，运行case
# if __name__=='__main__':
#     suite=unittest.TestSuite()
#
#     tests=[TestMathFunc("test_add"),TestMathFunc("test_minus"),TestMathFunc("test_divide"),TestMathFunc("test_multi")]
#     suite.addTests(tests)
#
#
#     runner=unittest.TextTestRunner(verbosity=2)
#     runner.run(suite)
curpath = os.path.dirname(os.path.realpath(__file__))
test_dir = os.path.join(os.path.abspath(os.path.join(curpath, os.path.pardir)), 'case_unittest')

# def add_case(test_dir):
#     # 通过该类下面的discover（）方法自动匹配查找以test*开头的文件，用run（）执行discover
#     discover = unittest.defaultTestLoader.discover(test_dir, pattern='test_*.py')
#     return discover


# 以HTML页面输出测试报告
if __name__=='__main__':


    suite=unittest.TestSuite()
    # 运行某个测试用例类的所有测试用例，通过该类下面的run（）方法运行
    # suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFunc))

    # 获取路径下所有test_开头文件，作为case
    # 通过该类下面的discover（）方法自动匹配查找以test*开头的文件，用run（）执行discover
    discover = unittest.defaultTestLoader.discover(test_dir, pattern='test_*.py')
    suite.addTests(discover)
    # with open('HTMLReport.html','wb') as f:
    #     runner=HTMLTestRunner(stream=f,
    #                           title='MathFunc Test',
    #                           description='generated by HTMLTestRunner',
    #                           verbosity=2
    #                           )
    #     runner.run(suite)


    result = BeautifulReport(suite)
    result.report(filename='接口测试报告', description='接口测试报告', log_path='./htmlreport')

















